### PR TITLE
Include Android.mk also for non AOSP ROMs

### PR DESCRIPTION
**Pull request by nilac8991**

### CODE REVIEW

**Comment by MatthewBooth** [comment]
Why would non-AOSP ROMs need the Makefile? Eclipse or Android Studio would be doing the building for those kinds of ROMs.

If you're thinking of CyanogenMod, AOKP, Paranoid Android and the like, they should use the aosp branch. They are all based off AOSP, and use these AOSP build system, which was the idea behind the branch name :)

**Comment by MatthewBooth** [comment]
Also, this should be set to merge into master, not stable :)

**Comment by nilac8991** [comment]
But the AOSP one is behind some commits than the stable one as i still facing problems with the addons page

**Comment by nilac8991** [comment]
No problem just helping :)

**Comment by MatthewBooth** [comment]
I merged master into aosp a couple of days ago to fix those issues.

**Comment by nilac8991** [comment]
Yep i see now 
Thanks. 
I will just close the pull request ;)

**Comment by MatthewBooth** [comment]
Thank you for using the time to use this system, though :)

If there is still a problem, please don't hesitate to make an issue or pull request!

Matt

**Comment by nilac8991** [comment]
Yeah i use it for my custom Resurrection Releases and i really appreciate your work done, the app is made in a very good manner :+1:

**Pull request closed without merging**
